### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by JimChenWYU** [kuangjy2/omnipay-qpay#6]
你好，请问你在开发QQ钱包企业付款到余额功能时，能不能完成转账？QQ钱包这个接口我在测试的时候一直在报 `SYSTEMERROR`，亲测过参数传错或传漏会报 `PARAM_ERROR`，签名出错会报 `SIGNERROR`，所以面对一直 `SYSTEMERROR` 无从下手 debug。

**Comment by kuangjy2** [comment]
你好，这个功能最开始是别人PR过来我再按规范修改的，现在我手里没有QQ钱包的商户号没法测试，所以也一直没有打tag，QQ钱包资料很少而且官方文档很多错漏。
百度搜到一篇微信企业付款的类似问题
https://www.cnblogs.com/lihuobao/p/5641790.html
如果鹅厂内部处理逻辑相同的话应该具有参考性，看看钱有没有到账

**Comment by kuangjy2** [comment]
你是五口巴校友吗😂

**Comment by JimChenWYU** [comment]
@kuangjy2 

- 是的，校友。

- 没转帐成功，连现金红包都不可以，又是莫名其妙报`订单支付失败`，官方文档什么描述都没有。
